"""stub_builder.py — a stand-in for D7's not-yet-existent model/codegen.

**This is NOT D7.** D7 (docs/design/the-forge.md) is "model routing is a
declared action, not ambient network access" — a local model tried first,
cloud fallback as a declared permission, only then a network-enabled Kart
invocation. None of that exists yet: nothing in this repo turns a builder's
description of an app into generated code. `bite 0` (the spine) needs
*something* runnable to prove the sandbox -> plan -> gate -> seam pipeline
end to end, so this module hard-codes the one build every pipeline needs to
prove itself against first — hello world — rather than pretending a stub is
D7 wearing a disguise. When D7 lands, `hello_world_command` is deleted, not
extended; nothing downstream (`stores/forge_build.py`) depends on this
module being anything more than a placeholder.

`hello_world_command(app_name)` returns a shell command string, matching
`sandbox_runner.py`'s own v1 build-task contract exactly: "a BuildTask is a
shell command... its ENTIRE stdout must be exactly one JSON object in
plan.py's wire format." The returned command is a self-contained
`python3 -c "..."` invocation — it assumes nothing about what's importable
inside the sandbox beyond a `python3` interpreter and its own standard
library (`json`), because that's the only thing D2's sandbox contract
promises a build. It does NOT import `the_forge`, `kartikeya`, or anything
from `safe-app-store` at *build-execution* time — the command is a plain
string this module hands to a caller; nothing it contains reaches back into
this package or the host once it's inside the sandbox.

The emitted plan deliberately has no `builder_id` key — `plan.py`'s
`plan_from_dict` refuses a plan that asserts its own identity (D11's
reasoning: the seam supplies `builder_id` from its own trusted context,
never from untrusted sandbox output), so a stub that tried to include one
would make every real build using it fail at the seam, not just this test
one.

Import-pure per D13: this module imports only `json` (to build the command
string on the *host* side, not inside the sandbox — see below) and nothing
from `safe-app-store`. It does not import `kartikeya`, `sandbox_runner`,
`plan`, or anything else in this package — it has no dependency on how its
output gets run, only on what `sandbox_runner.parse_plan_stdout` expects to
read back.
"""
from __future__ import annotations

import json

__all__ = ["hello_world_command"]


def hello_world_command(app_name: str) -> str:
    """Return a shell command that, when run inside Kart, prints a valid
    hello-world `Plan` JSON object to stdout and nothing else.

    The command embeds `app_name` (and the rest of the plan payload) as a
    Python literal via `repr()`, then passes the whole `python3 -c <script>`
    invocation through the host's own quoting so it survives `bash -c`
    unchanged — the same escaping concern `sandbox_runner`'s own tests
    solve with `shlex.quote`, applied here on the string-construction side
    rather than assuming the caller will do it. This works regardless of
    what characters end up in `content` (quotes, newlines, whatever) because
    `repr()` on a dict of `str`/`bool` values always produces syntactically
    valid Python source — there is no second, hand-rolled escaping layer to
    get wrong.

    Two `file_write` entries, matching the wire format `plan_from_dict`
    reads:
      - `README.md`  — a note identifying this as a stub-builder output.
      - `app.py`     — `print('hello from <app_name>')`, not executable.
    """
    plan_payload = {
        "app_name": app_name,
        "entries": [
            {
                "kind": "file_write",
                "dest_path": "README.md",
                "content": (
                    f"# {app_name}\n\n"
                    f"Generated by The Forge's stub builder (bite 0) — a placeholder for "
                    f"D7's not-yet-existent model/codegen, not D7 itself. See "
                    f"the_forge/stub_builder.py.\n"
                ),
            },
            {
                "kind": "file_write",
                "dest_path": "app.py",
                "content": f"print('hello from {app_name}')",
                "executable": False,
            },
        ],
    }
    # `repr(plan_payload)` is a Python dict literal — valid source once
    # spliced into a `python3 -c` script. `shlex.quote` is deliberately NOT
    # imported/used here: the *whole* script (including its embedded quotes
    # from repr()) is what needs to survive the trip through `bash -c cmd`
    # (sandbox_runner.py / kartikeya.sandbox.run_shell both use
    # `bash -c <the whole command string>`), and the safest way to do that
    # without a second escaping pass is to build the entire `python3 -c "..."`
    # invocation as one `repr()`'d string in turn, the same trick applied
    # one level up.
    script = f"import json; print(json.dumps({plan_payload!r}))"
    return f"python3 -c {_shell_quote(script)}"


def _shell_quote(s: str) -> str:
    """POSIX single-quote a string for `bash -c`: wrap in `'...'`, escaping
    any embedded `'` as `'\\''`. Equivalent to `shlex.quote` for this
    module's purposes, reimplemented locally so `hello_world_command`'s only
    import is `json` — a deliberately small footprint for a module that
    exists to be deleted once D7 lands, not to accumulate dependencies."""
    return "'" + s.replace("'", "'\\''") + "'"
